### ISSUE TITLE
backintime available for 22.04 ?

### ISSUE THREAD

**Issue by speedy-10** [bit-team/backintime#1223]
Hi I just installed backintime on a VM with Ubuntu 22.04:
After starting `backintime-qt` in terminal, I got serveral errors, see picture.

It would be nice to have this perfect tool again in 22.04.

Regard
![ksnip_20220206-125050](https://user-images.githubusercontent.com/20227451/152679557-6d73b87d-adb5-4dfb-9106-49df06abec85.png)
s

**Comment by gsker** [comment]
Was this a clean install?  
I just fired up a jammy instance and installed backintime-qt from the repo and ran it.  
If you upgraded I wonder if there are some python3 packages not not updated.

**Comment by speedy-10** [comment]
It was a new installation in a VM.

**Comment by freiheitsnetz** [comment]
Since some day I have the same issue. I upgraded from Ubuntu 21.10. This issue #1210 describes the same. It's somehow related to the latest python3 packages.

**Comment by emtiu** [comment]
I think #1174 is meant to fix this, but I'm unsure whether this project has any maitainers at the moment.

**Comment by Germar** [comment]
This was fixed in 1.3.1 but this release wasn't picked up by Ubuntu/Debian. I just pushed a package for 21.10 and 22.04 to both PPAs. You can use it with
```
sudo add-apt-repository ppa:bit-team/stable
```

**Comment by speedy-10** [comment]
Hi thanks, I could instal from the ppa, but the failure remained?

**Comment by freiheitsnetz** [comment]
Hi. Nice to see that this issue should be picked up.
Unfortunately the issue remains for me as well. It's exactly the same error messages as above, except that it occurs now in line 1805 instead of 1802 of tools.py.

**Comment by freiheitsnetz** [comment]
I've just tried to use the current version directly from the sources and that works :-)
So, the version from the bit-team/stable ppa does not seem to be the same as the master branch here.

**Comment by speedy-10** [comment]
Hi, I can't confirm that: A complete new installation of backintime-qt lead to the same failure as I mentioned at the beginning.
Kernel: 5.15.0-22

**Comment by freiheitsnetz** [comment]
I've done a few more tests and still can confirm that on a fresh Ubuntu 22.04 virtual machine with all update installed:
- The installation from the [suggested ppa](https://github.com/bit-team/backintime/issues/1223#issuecomment-1062102815) does **not** work.
- The installation from [sources](https://github.com/bit-team/backintime#from-sources) using the master branch of this repo **does** work (after installing the required dependencies).

**Comment by Germar** [comment]
I'll set up a 22.04 VM this weekend and have a look.

**Comment by Germar** [comment]
The fix was not released in 1.3.1 so I made a new release which is working on my 22.04 VM

**Comment by speedy-10** [comment]
Thanks, now the installation via ppa works on my VM, too.
