### ISSUE TITLE
Backintime doesn't start (opensuse tumbleweed)

### ISSUE THREAD

**Issue by highmcfly** [bit-team/backintime#756]
Backintime (version 1.1.6-1.4) doesn't start (opensuse tumbleweed).

What is the problem?

```
WARNING: import keyring failed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 437, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 156, in start_app
    cfg = config.Config(config_path)
  File "/usr/share/backintime/common/config.py", line 268, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1036, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1
```

**Comment by Germar** [comment]
Please clone current master from GitHub and update manually to 1.2.0~alpha. This is already fixed in there.

**Comment by CristianCantoro** [comment]
I have installed bit `1.2.0~alpha17` and I still the same error

**Comment by buhtzz** [comment]
@CristianCantoro There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Close as duplicate.

**Comment by CristianCantoro** [comment]
@buhtzz wrote:
> @CristianCantoro There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?
> 
> Close as duplicate.

Not an issue anymore, but to be fair, I am on a new machine with a new OS.

**Comment by emtiu** [comment]
Closing as duplicate of #921.

**Comment by aryoda** [comment]
**Internal note while analyzing why this exception was not handled gracefully in the fixed code of v1.2.0 (working on a fix for `master` in #921):**

The error is thrown (at the BiT client side) in 

> File "/usr/share/backintime/common/tools.py", line 1036, in __init__
>    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)

with this corresponding code in v1.1.6

https://github.com/bit-team/backintime/blob/565f23e8352125977b5ec93b93e9eaad4faf3c10/common/tools.py#L1033-L1044

while the code in v1.2.0 is now contained in `SetupUdev()` instead of `__init__` and also handles the `NameHasNoOwner` exception now:

https://github.com/bit-team/backintime/blob/f7f28b50b7decd8f7e8666c654c33fda387f2ea0/common/tools.py#L1713-L1724

Despite

- moving the code from `__init__` to `SetupUdev()` it is **still always called during start-up** in the [`config.__init__`](https://github.com/bit-team/backintime/blob/f7f28b50b7decd8f7e8666c654c33fda387f2ea0/common/config.py#L279)
- catching the `dbus.exceptions.DBusException` and the added graceful recovery for `NameHasNoOwner` an exception is still thrown and stops BiT during start-up. **WHY?**
